print("Name : Yasser Hamed Abdel hameed")
print("From : Ras elbar")
print("DOB : 26 / 07 / 1996")
print("Faculty of computing and information systems")
print("Graduate : 2018")
print("Officer at the military services from 2019 -2022")
print("Student at ITI now!")