Num1 , Num2= input("Enter 1st Number : ").split("$$",2)
#Num2 = input("Enter 2nd Number : ")

Num1 = int(Num1)
Num2 = int(Num2)
'''
print(int(Num1) + int(Num2))
print(int(Num1) - int(Num2))
print(int(Num1) * int(Num2))
print(int(Num1) / int(Num2))
print("------------------")
print(int(Num1) & int(Num2))
print(int(Num1) | int(Num2))
print(int(Num1) ^ int(Num2))
print(~int(Num1))
print(int(Num1) >> int(Num2))
print(int(Num1) << int(Num2))
print("------------------")
print(int(Num1) > int(Num2))
print(int(Num1) < int(Num2))
print(int(Num1) == int(Num2))
''''''
print("Sum = %d" %(Num1+Num2))
print("sub = %d" %(Num1-Num2))
print("mul = %d" %(Num1*Num2))
print("div = %f" %(Num1/Num2))
print("---------------------")
print("and = %d" %(Num1&Num2))
print("or = %d" %(Num1|Num2))
print("Xor = %d" %(Num1^Num2))
print("Not = %d" %(~Num1))
print("R-shft = %d" %(Num1>>Num2))
print("L-Shft = %d" %(Num1<<Num2))
print("---------------------")
print("Less = %b" %(Num1<Num2))
print("Bigger = %d" %(Num1>Num2))
print("Equality = %d" %(Num1==Num2))
'''
print("Sum = " ,Num1 + Num2)
